// vue-todolist/src/App.vue
<script setup lang="ts">
import TodoList from './components/TodoList.vue';
</script>

<template>
  <div>
    <TodoList></TodoList>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// svelte-todolist/src/App.svelte
<script lang="ts">
  import TodoList from './lib/TodoList.svelte';
</script>

<main>
  <div class="card">
    <!-- <Counter /> -->
    <TodoList />
  </div>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>
